name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The image version to deploy, e.g., v1.2.3'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Checkout 'prod' branch
        # After this step runs, the full contents of the branch
        # is available in the current working directory.
        uses: actions/checkout@v2
        with:
          ref: prod

      - name: Login to Amazon ECR
        # After this step runs, assume you are authenticated to
        # the ECR registry "123456789012.dkr.ecr.us-west-2.amazonaws.com"
        # with push and pull permissions.
        uses: aws-actions/amazon-ecr-login@v1

      - name: Echo version
        run: |
          echo "Deploying version: ${{ github.event.inputs.version }}"

      - name: placeholder1
        run: |
          echo "placeholder1"

      - name: placeholder2
        run: |
          echo "placeholder2"
